#!/bin/bash

# Mandatory Options
#SBATCH --export=NONE
#SBATCH --open-mode=append

# Generated by the `slurmworkflow` R package
#SBATCH --partition=epimodel
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=dehao.chen@emory.edu
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --time=180

# see https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -e

SWF_ROOT="$1"
SWF_CUR="$2"
source "$SWF_ROOT/SWF/lib.sh"
make_env_vars "$SWF_ROOT"
make_env_cur_vars "$SWF_CUR"

source "$SWF__STEP_SCRIPT"
